#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 blur_radius=20 color=$TRANSPARENT
# bar=(
# 	height=37
# 	color="$TRANSPARENT"
# 	border_width=2
# 	border_color="$TRANSPARENT"
# 	shadow=off
# 	position=top
# 	sticky=on
# 	padding_right=10
# 	padding_left=10
# 	y_offset=0
# 	margin=-2
# 	topmost=window
# )

# sketchybar --bar "${bar[@]}"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=2
  padding_right=2
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.color=$BAR_COLOR
  background.corner_radius=10
  background.height=24
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=2
  label.padding_right=4
)
sketchybar --default "${default[@]}"
##### Left-side items #####
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
# source $ITEM_DIR/network.sh

# Right-side items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/cpu.sh

sketchybar --add bracket activity ram cpu                      \
           --set         activity background.color=$ITEM_BG_COLOR     \
                         background.border_width=0                  \
                         background.color=$BAR_COLOR                \
# source $ITEM_DIR/keyboard.sh
##### Adding Mission Control Space Indicators #####

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update